# Generated by Django 3.2.3 on 2021-06-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dis_image', models.ImageField(upload_to='images/')),
                ('capacity', models.IntegerField(default=100)),
                ('attendance', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('event_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_seat', models.IntegerField(default=1)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.event')),
            ],
        ),
    ]
