# Generated by Django 3.2.3 on 2021-06-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210613_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
